name: 'Release a Changelog'
description: 'Creates a GitHub release based on Keep a Changelog'

runs:
  using: node20
  main: 'index.js'

branding:
  icon: align-justify
  color: green

inputs:
  github-token:
    description: "GitHub token"
    required: true
  path:
    description: "Path to the changelog file"
    required: false
    default: "CHANGELOG.md"
  title-template:
    description: "Template for the release title. {version} is replaced with the version from the changelog"
    required: false
    default: "{version}"
  tag-template:
    description: "Template for the release tag. {version} is replaced with the version from the changelog"
    required: false
    default: "{version}"
